# Generated by Django 5.2.6 on 2025-10-01 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selfToken',
            new_name='ShelfToken',
        ),
    ]
