# Generated by Django 5.2.6 on 2025-10-02 06:15

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_selftoken_shelftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelftoken',
            name='token',
            field=models.IntegerField(default=home.models.generate_token, unique=True),
        ),
    ]
