# Generated by Django 5.2.6 on 2025-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shelftoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelftoken',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
