# Generated by Django 5.2.6 on 2025-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shelftoken_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelftoken',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
