# Generated by Django 5.2.6 on 2025-10-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shelftoken_approved_by_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelftoken',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='shelftoken',
            name='collected',
        ),
        migrations.AddField(
            model_name='shelftoken',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('collected', 'Collected/Returned')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelftoken',
            name='shelf_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shelftoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
