# Generated by Django 5.2.6 on 2025-10-02 12:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_shelftoken_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelftoken',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('retrieval_requested', 'Retrieval Requested'), ('retrieved', 'Retrieved')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='shelftoken',
            name='token',
            field=models.CharField(default=home.models.generate_token, max_length=4, unique=True),
        ),
    ]
