# Generated by Django 5.2.6 on 2025-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_shelftoken_status_alter_shelftoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelftoken',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('retrieval_requested', 'Retrieval Requested'), ('collected', 'Collected')], default='requested', max_length=20),
        ),
    ]
