# Generated by Django 5.2.6 on 2025-10-02 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_shelftoken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelftoken',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelftoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shelftoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
