# Generated by Django 5.2.6 on 2025-10-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shelftoken_assigned_at_shelftoken_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelftoken',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='shelftoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shelftoken',
            name='updated_at',
        ),
    ]
